### ISSUE TITLE
Changing the base model from inpainting-big to sd-1.5-inpainting

### ISSUE THREAD

**Issue by phcerdan** [lorenzo-stacchio/stable-diffusion_custom_inpaint#7]
The base model `inpainting_big` is from 2022: https://ommer-lab.com/files/latent-diffusion/

Can the [sd-.15-inpainting.ckpt](https://huggingface.co/runwayml/stable-diffusion-inpainting/blob/main/sd-v1-5-inpainting.ckpt), be used instead? Would it require any change in the config train?

**Comment by littleYaang** [comment]
hi! how do you solve it ?
